language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

install:
    # Use mirrors to not avoid burdening PyPI
    - pip install --use-mirrors -r requirements.txt
    - pip install -e .

before_script:
    - flake8 --ignore=F401 .
    - pep257 --ignore=D102,D103,D400 .

script: py.test .

branches:
    only:
        - master
