language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

install:
    # Use mirrors to not avoid burdening PyPI
    - pip install --use-mirrors -r requirements.txt
    - pip install -e .

before_script:
    - flake8 .
    - pep257 .

script: py.test .

branches:
    only:
        - master
