language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

install:
    # Use mirrors to not avoid burdening PyPI
    - pip install --use-mirrors -r requirements.txt

    # Coveralls 4.0 doesn't support Python 3.2
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
    #- pip install -e .

before_script:
    - flake8 --ignore=F401 .
    - pep257 --ignore=D102,D103,D211,D400 .

script:
    - coverage run --source=progress -m py.test

after_success:
    - coveralls

branches:
    only:
        - master
        - prop_exts
