language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

install:
    # Use mirrors to not avoid burdening PyPI
    - pip install -r requirements.txt

    # Coveralls 4.0 doesn't support Python 3.2
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi

    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install 'virtualenv<14'; fi

    # flake8 no longer supports 2.6, this is a temporary fix
    - if [ "$TRAVIS_PYTHON_VERSION" != "2.6" ]; then travis_retry pip install flake8; fi

before_script:
    - if [ "$TRAVIS_PYTHON_VERSION" != "2.6" ]; then travis_retry flake8 --ignore=F401 .; fi
    - pep257 --ignore=D102,D103,D211,D400 .

script:
    - virtualenv --version
    - coverage --version
    - coverage run --source=progress -m py.test

after_success:
    - coveralls

branches:
    only:
        - master
        - prop_exts
